### ISSUE TITLE
Example breaks when using Mbed OS 6.3.0

### ISSUE THREAD

**Issue by COTASPAR** [ARMmbed/mbed-os-example-for-aws#28]
Steps to replicate issue: 
   `git clone https://github.com/ARMmbed/mbed-os-example-for-aws.git && cd mbed-os-example-for-aws `
  ` mbed deploy`
   `mbed compile -m detect -t GCC_ARM --flash --sterm --baud 115200`

**Comment by cyliangtw** [comment]
Also build failed in on-line compiler.
It seems relative to `threadRoutine(pArgument);` in iot_thread.cpp .

![image](https://user-images.githubusercontent.com/14323432/96569860-3bd7f780-12fc-11eb-82cc-ecef955e2e4e.png)

**Comment by evedon** [comment]
This issue is related to https://github.com/ARMmbed/mbed-os/issues/13764
The Mbed OS version deployed is an old version of Mbed OS (5.14.4 when I tried) and gives the compilation error mentioned.
You can try `mbed ls` to see which version of mbed-os library is used after running the `mbed deploy` command. 
I tried to compile the example with Mbed OS `6.3.0` and it worked.

**Comment by cyliangtw** [comment]
Yes, it did working thru CLI on OS 6.3.0 .
However, I tried all of newer versions than OS v6.2.1  in on-line compiler, still got the same compiler error.
Is there any way to reflect this symptom to on-line compiler team ?
![image](https://user-images.githubusercontent.com/14323432/96665875-738c8100-1388-11eb-82cd-5cab011f28d2.png)

**Comment by 0xc0170** [comment]
> However, I tried all of newer versions than OS v6.2.1 in on-line compiler, still got the same compiler error.

What versions are newer than 6.2.1 ? The capture above shows feature-wisun (it's 5.15 based, it won't work with this example, same as 5.15). There's just 6.3.0 and now 6.4.0rc1 in preparation.

> Is there any way to reflect this symptom to on-line compiler team ?

Use only official releases (mbed-os-6.x.x tags) in the online compiler, same as you would do with mbed-cli .

**Comment by cyliangtw** [comment]
> What versions are newer than 6.2.1 ? The capture above shows feature-wisun (it's 5.15 based, it won't work with this example, same as 5.15). There's just 6.3.0 and now 6.4.0rc1 in preparation.
> 
I tried to switch 4 tags as `aa70f68, 0db72d0c(mbed-os-6.3.0), c6d65fe and 8ef0a435b(mbed-os-6.4.0-rc1)`, all of these 4 tags got the same compile error "No matching member" in Mbed on-line compiler. 
> Use only official releases (mbed-os-6.x.x tags) in the online compiler, same as you would do with mbed-cli .

Where to report this kind issue to notify no-line compiler team ?

**Comment by ciarmcom** [comment]
@COTASPAR thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by COTASPAR** [comment]
This issue was not caused by Mbed OS 6.3.0 but rather by [this issue](https://github.com/ARMmbed/mbed-os/issues/13764). Therefore I'm closing the current issue.
